# Site settings
title: 韦小康的博客
header-img: img/home-bg.jpg
email: weixkz@qq.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ""
github_username:  weixiaokang
facebook_username:  小康韦

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
